module.exports = [
    { label: 'true', value: true },
    { label: '\'true\'', value: 'true' },
    { label: '0', value: 0 },
    { label: '\'0\'', value: '0' },
    { label: '1', value: 1 },
    { label: '\'1\'', value: '1' },
    { label: 'null', value: null },
    { label: '\'null\'', value: 'null' },
    { label: 'true', value: true },
    { label: '\'true\'', value: 'true' },
    { label: 'false', value: false },
    { label: '\'false\'', value: 'false' },
    { label: 'undefined', value: undefined },
    { label: '\'undefined\'', value: 'undefined' },
    { label: '\'\'', value: '' },
    { label: '\' \'', value: ' ' },
    { label: '\'foo\'', value: 'foo' },
    { label: '\'Array\'', value: 'Array' },
    { label: 'Array.prototype', value: Array.prototype },
    { label: '[1]', value: [1] },
    { label: 'new Array()', value: new Array() },
    { label: 'new Date()', value: new Date() },
    { label: 'new Boolean()', value: new Boolean() },
    { label: 'new Number()', value: new Number() },
    { label: 'new String()', value: new String() },
    { label: 'function(){}', value: function(){} },
    { label: 'Math.LN2', value: Math.LN2 },
    { label: '37', value: 37 },
    { label: '3.14', value: 3.14 },
    { label: 'Infinity', value: Infinity },
    { label: 'Number(1)', value: Number(1) },
    { label: 'Number()', value: Number() },
    { label: 'Number(1.1)', value: Number(1.1) }
];
